[package]
name = "wgpu"
version = "0.1.0"
authors = ["Mohammed Alyousef <may642_2000@hotmail.com>", "Rongcui Dong <rongcuid@outlook.com>"]
edition = "2018"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = { version = "1", features = ["fltk-bundled", "raw-window-handle"] }
wgpu = "0.13"

pollster = "0.2"
