[package]
name = "speedy"
version = "0.1.0"
authors = ["Mohammed Alyousef <may642_2000@hotmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = { version = "1", features = ["enable-glwindow"] }
speedy2d = { version = "1.0.2", default-features = false }
gl = "0.14"
